<?php

namespace App\Filament\Resources\Assets\RelationManagers;

use Illuminate\Database\Eloquent\Model;
use Filament\Schemas\Schema;
use Filament\Actions\Action;
use App\Enums\Assets\DepreciationEntryStatus;
use App\Models\DepreciationEntry;
use App\Services\AssetService;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;

class DepreciationEntryRelationManager extends RelationManager
{
    protected static string $relationship = 'depreciationEntries';

    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('asset.depreciation_entries');
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                // No form needed as entries are generated by the service
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('depreciation_date')
            ->columns([
                TextColumn::make('depreciation_date')
                    ->label(__('asset.depreciation_date'))
                    ->date(),
                TextColumn::make('amount')
                    ->label(__('asset.amount')),
                TextColumn::make('status')
                    ->label(__('asset.status')),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                // No header actions needed
            ])
            ->recordActions([
                Action::make('post')
                    ->label(__('asset.post'))
                    ->action(fn (DepreciationEntry $record) => $this->postDepreciation($record))
                    ->requiresConfirmation()
                    ->visible(fn (DepreciationEntry $record): bool => $record->status === DepreciationEntryStatus::Draft),
            ])
            ->toolbarActions([
                // No bulk actions needed
            ]);
    }

    public function postDepreciation(DepreciationEntry $entry): void
    {
        app(AssetService::class)->postDepreciation($entry, request()->user());
        $this->notify('success', __('asset.post_depreciation_success'));
    }
}
