<?php

namespace App\Filament\Resources\AssetResource\RelationManagers;

use App\Enums\Assets\DepreciationEntryStatus;
use App\Models\DepreciationEntry;
use App\Services\AssetService;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Actions\Action;
use Filament\Tables\Columns\TextColumn;

class DepreciationEntryRelationManager extends RelationManager
{
    protected static string $relationship = 'depreciationEntries';

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                // No form needed as entries are generated by the service
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('depreciation_date')
            ->columns([
                TextColumn::make('depreciation_date')->date(),
                TextColumn::make('amount')->money('IQD'),
                TextColumn::make('status'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                // No header actions needed
            ])
            ->actions([
                Action::make('post')
                    ->label('Post')
                    ->action(fn (DepreciationEntry $record) => $this->postDepreciation($record))
                    ->requiresConfirmation()
                    ->visible(fn (DepreciationEntry $record): bool => $record->status === DepreciationEntryStatus::Draft),
            ])
            ->bulkActions([
                // No bulk actions needed
            ]);
    }

    public function postDepreciation(DepreciationEntry $entry): void
    {
        app(AssetService::class)->postDepreciation($entry, request()->user());
        $this->notify('success', 'Depreciation posted successfully.');
    }
}
