<?php

namespace Modules\HR\Filament\Clusters\HumanResources\Resources\Employees\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class EmployeeForm
{
    public static function configure(Schema $schema): Schema
    {

        return $schema->components([
            Section::make(__('hr::employee.basic_information'))
                ->description(__('hr::employee.basic_information_description'))
                ->schema([
                    TextInput::make('employee_number')
                        ->label(__('hr::employee.employee_number'))
                        ->placeholder(__('hr::employee.autogenerated'))
                        ->disabled()
                        ->dehydrated(false)
                        ->visible(fn ($record) => $record !== null)
                        ->columnSpan(1),

                    TextInput::make('first_name')
                        ->label(__('hr::employee.first_name'))
                        ->required()
                        ->maxLength(255)
                        ->columnSpan(1),

                    TextInput::make('last_name')
                        ->label(__('hr::employee.last_name'))
                        ->required()
                        ->maxLength(255)
                        ->columnSpan(1),

                    TextInput::make('email')
                        ->label(__('hr::employee.email'))
                        ->email()
                        ->required()
                        ->unique(ignoreRecord: true)
                        ->maxLength(255)
                        ->columnSpan(2),

                    TextInput::make('phone')
                        ->label(__('hr::employee.phone'))
                        ->tel()
                        ->maxLength(20)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employee.organizational_details'))
                ->description(__('hr::employee.organizational_details_description'))
                ->schema([
                    Select::make('department_id')
                        ->label(__('hr::employee.department'))
                        ->relationship('department', 'name')
                        ->searchable()
                        ->preload()
                        ->columnSpan(1),

                    Select::make('position_id')
                        ->label(__('hr::employee.position'))
                        ->relationship('position', 'title')
                        ->searchable()
                        ->preload()
                        ->columnSpan(1),

                    Select::make('manager_id')
                        ->label(__('hr::employee.manager'))
                        ->relationship('manager', 'first_name')
                        ->searchable(['first_name', 'last_name', 'employee_number'])
                        ->preload()
                        ->getOptionLabelUsing(fn ($record) => $record ? $record->first_name.' '.$record->last_name.' ('.$record->employee_number.')' : '')
                        ->columnSpan(1),
                ])
                ->columns(2)
                ->columnSpanFull(),

            Section::make(__('hr::employee.personal_information'))
                ->description(__('hr::employee.personal_information_description'))
                ->schema([
                    DatePicker::make('date_of_birth')
                        ->label(__('hr::employee.date_of_birth'))
                        ->maxDate(now()->subYears(16))
                        ->columnSpan(1),

                    Select::make('gender')
                        ->label(__('hr::employee.gender'))
                        ->options([
                            'male' => __('hr::employee.gender_male'),
                            'female' => __('hr::employee.gender_female'),
                            'other' => __('hr::employee.gender_other'),
                        ])
                        ->columnSpan(1),

                    Select::make('marital_status')
                        ->label(__('hr::employee.marital_status'))
                        ->options([
                            'single' => __('hr::employee.marital_status_single'),
                            'married' => __('hr::employee.marital_status_married'),
                            'divorced' => __('hr::employee.marital_status_divorced'),
                            'widowed' => __('hr::employee.marital_status_widowed'),
                        ])
                        ->columnSpan(1),

                    TextInput::make('nationality')
                        ->label(__('hr::employee.nationality'))
                        ->maxLength(100)
                        ->columnSpan(1),

                    TextInput::make('national_id')
                        ->label(__('hr::employee.national_id'))
                        ->maxLength(50)
                        ->columnSpan(1),

                    TextInput::make('passport_number')
                        ->label(__('hr::employee.passport_number'))
                        ->maxLength(50)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employee.address_information'))
                ->description(__('hr::employee.address_information_description'))
                ->schema([
                    TextInput::make('address_line_1')
                        ->label(__('hr::employee.address_line_1'))
                        ->maxLength(255)
                        ->columnSpan(2),

                    TextInput::make('address_line_2')
                        ->label(__('hr::employee.address_line_2'))
                        ->maxLength(255)
                        ->columnSpan(1),

                    TextInput::make('city')
                        ->label(__('hr::employee.city'))
                        ->maxLength(100)
                        ->columnSpan(1),

                    TextInput::make('state')
                        ->label(__('hr::employee.state'))
                        ->maxLength(100)
                        ->columnSpan(1),

                    TextInput::make('zip_code')
                        ->label(__('hr::employee.zip_code'))
                        ->maxLength(20)
                        ->columnSpan(1),

                    TextInput::make('country')
                        ->label(__('hr::employee.country'))
                        ->maxLength(100)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employee.emergency_contact'))
                ->description(__('hr::employee.emergency_contact_description'))
                ->schema([
                    TextInput::make('emergency_contact_name')
                        ->label(__('hr::employee.emergency_contact_name'))
                        ->maxLength(255)
                        ->columnSpan(1),

                    TextInput::make('emergency_contact_phone')
                        ->label(__('hr::employee.emergency_contact_phone'))
                        ->tel()
                        ->maxLength(20)
                        ->columnSpan(1),

                    TextInput::make('emergency_contact_relationship')
                        ->label(__('hr::employee.emergency_contact_relationship'))
                        ->maxLength(100)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employee.employment_details'))
                ->description(__('hr::employee.employment_details_description'))
                ->schema([
                    DatePicker::make('hire_date')
                        ->label(__('hr::employee.hire_date'))
                        ->required()
                        ->maxDate(now())
                        ->columnSpan(1),

                    DatePicker::make('termination_date')
                        ->label(__('hr::employee.termination_date'))
                        ->minDate(fn ($get) => $get('hire_date'))
                        ->columnSpan(1),

                    Select::make('employment_status')
                        ->label(__('hr::employee.employment_status'))
                        ->options([
                            'active' => __('hr::employee.employment_status_active'),
                            'inactive' => __('hr::employee.employment_status_inactive'),
                            'terminated' => __('hr::employee.employment_status_terminated'),
                            'on_leave' => __('hr::employee.employment_status_on_leave'),
                        ])
                        ->required()
                        ->default('active')
                        ->columnSpan(1),

                    Select::make('employee_type')
                        ->label(__('hr::employee.employee_type'))
                        ->options([
                            'full_time' => __('hr::employee.employee_type_full_time'),
                            'part_time' => __('hr::employee.employee_type_part_time'),
                            'contract' => __('hr::employee.employee_type_contract'),
                            'intern' => __('hr::employee.employee_type_intern'),
                        ])
                        ->required()
                        ->default('full_time')
                        ->columnSpan(1),

                    Toggle::make('is_active')
                        ->label(__('hr::employee.is_active'))
                        ->default(true)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employee.banking_information'))
                ->description(__('hr::employee.banking_information_description'))
                ->schema([
                    TextInput::make('bank_name')
                        ->label(__('hr::employee.bank_name'))
                        ->maxLength(255)
                        ->columnSpan(1),

                    TextInput::make('bank_account_number')
                        ->label(__('hr::employee.bank_account_number'))
                        ->maxLength(50)
                        ->columnSpan(1),

                    TextInput::make('bank_routing_number')
                        ->label(__('hr::employee.bank_routing_number'))
                        ->maxLength(50)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),
        ]);
    }
}
