<?php

namespace Kezi\HR\Filament\Clusters\HumanResources\Resources\EmploymentContracts\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Kezi\Foundation\Filament\Forms\Components\MoneyInput;

class EmploymentContractForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make(__('hr::employment_contract.basic_information'))
                ->description(__('hr::employment_contract.basic_information_description'))
                ->schema([
                    \Kezi\HR\Filament\Forms\Components\EmployeeSelectField::make('employee_id')
                        ->label(__('hr::employment_contract.fields.employee'))
                        ->columnSpan(1),

                    TextInput::make('contract_number')
                        ->label(__('hr::employment_contract.fields.contract_number'))
                        ->placeholder(__('hr::employment_contract.fields.autogenerated'))
                        ->disabled()
                        ->dehydrated(false)
                        ->visible(fn ($record) => $record !== null)
                        ->columnSpan(1),

                    Select::make('contract_type')
                        ->label(__('hr::employment_contract.fields.contract_type'))
                        ->options([
                            'permanent' => __('hr::employment_contract.types.permanent'),
                            'fixed_term' => __('hr::employment_contract.types.fixed_term'),
                            'temporary' => __('hr::employment_contract.types.temporary'),
                            'consultancy' => __('hr::employment_contract.types.consultancy'),
                            'internship' => __('hr::employment_contract.types.internship'),
                        ])
                        ->required()
                        ->live()
                        ->columnSpan(1),

                    DatePicker::make('start_date')
                        ->label(__('hr::employment_contract.fields.start_date'))
                        ->required()
                        ->columnSpan(1),

                    DatePicker::make('end_date')
                        ->label(__('hr::employment_contract.fields.end_date'))
                        ->after('start_date')
                        ->required(fn ($get) => $get('contract_type') !== 'permanent')
                        ->visible(fn ($get) => $get('contract_type') !== 'permanent')
                        ->columnSpan(1),

                    Toggle::make('is_active')
                        ->label(__('hr::employment_contract.fields.is_active'))
                        ->default(true)
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employment_contract.compensation_details'))
                ->description(__('hr::employment_contract.compensation_details_description'))
                ->schema([
                    \Kezi\Foundation\Filament\Forms\Components\CurrencySelectField::make('currency_id')
                        ->label(__('hr::employment_contract.fields.currency'))
                        ->required()
                        ->columnSpan(1),

                    MoneyInput::make('base_salary')
                        ->label(__('hr::employment_contract.fields.base_salary'))
                        ->currencyField('currency_id')
                        ->required()
                        ->columnSpan(1),

                    MoneyInput::make('hourly_rate')
                        ->label(__('hr::employment_contract.fields.hourly_rate'))
                        ->currencyField('currency_id')
                        ->columnSpan(1),

                    Select::make('pay_frequency')
                        ->label(__('hr::employment_contract.fields.pay_frequency'))
                        ->options([
                            'monthly' => __('hr::employment_contract.frequencies.monthly'),
                            'bi_weekly' => __('hr::employment_contract.frequencies.bi_weekly'),
                            'weekly' => __('hr::employment_contract.frequencies.weekly'),
                            'hourly' => __('hr::employment_contract.frequencies.hourly'),
                        ])
                        ->required()
                        ->default('monthly')
                        ->columnSpan(1),

                    MoneyInput::make('housing_allowance')
                        ->label(__('hr::employment_contract.fields.housing_allowance'))
                        ->currencyField('currency_id')
                        ->default(0)
                        ->columnSpan(1),

                    MoneyInput::make('transport_allowance')
                        ->label(__('hr::employment_contract.fields.transport_allowance'))
                        ->currencyField('currency_id')
                        ->default(0)
                        ->columnSpan(1),

                    MoneyInput::make('meal_allowance')
                        ->label(__('hr::employment_contract.fields.meal_allowance'))
                        ->currencyField('currency_id')
                        ->default(0)
                        ->columnSpan(1),

                    MoneyInput::make('other_allowances')
                        ->label(__('hr::employment_contract.fields.other_allowances'))
                        ->currencyField('currency_id')
                        ->default(0)
                        ->columnSpan(1),
                ])
                ->columns(4)
                ->columnSpanFull(),

            Section::make(__('hr::employment_contract.working_conditions'))
                ->description(__('hr::employment_contract.working_conditions_description'))
                ->schema([
                    TextInput::make('working_hours_per_week')
                        ->label(__('hr::employment_contract.fields.working_hours_per_week'))
                        ->numeric()
                        ->default(40)
                        ->required()
                        ->columnSpan(1),

                    TextInput::make('working_days_per_week')
                        ->label(__('hr::employment_contract.fields.working_days_per_week'))
                        ->numeric()
                        ->default(5)
                        ->required()
                        ->columnSpan(1),

                    TextInput::make('annual_leave_days')
                        ->label(__('hr::employment_contract.fields.annual_leave_days'))
                        ->numeric()
                        ->default(21)
                        ->required()
                        ->columnSpan(1),

                    TextInput::make('sick_leave_days')
                        ->label(__('hr::employment_contract.fields.sick_leave_days'))
                        ->numeric()
                        ->default(10)
                        ->required()
                        ->columnSpan(1),

                    TextInput::make('maternity_leave_days')
                        ->label(__('hr::employment_contract.fields.maternity_leave_days'))
                        ->numeric()
                        ->default(90)
                        ->required()
                        ->columnSpan(1),

                    TextInput::make('paternity_leave_days')
                        ->label(__('hr::employment_contract.fields.paternity_leave_days'))
                        ->numeric()
                        ->default(7)
                        ->required()
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employment_contract.probation_and_notice'))
                ->description(__('hr::employment_contract.probation_and_notice_description'))
                ->schema([
                    TextInput::make('probation_period_months')
                        ->label(__('hr::employment_contract.fields.probation_period_months'))
                        ->numeric()
                        ->columnSpan(1),

                    DatePicker::make('probation_end_date')
                        ->label(__('hr::employment_contract.fields.probation_end_date'))
                        ->after('start_date')
                        ->columnSpan(1),

                    TextInput::make('notice_period_days')
                        ->label(__('hr::employment_contract.fields.notice_period_days'))
                        ->numeric()
                        ->default(30)
                        ->required()
                        ->columnSpan(1),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Section::make(__('hr::employment_contract.additional_information'))
                ->description(__('hr::employment_contract.additional_information_description'))
                ->schema([
                    RichEditor::make('job_description')
                        ->label(__('hr::employment_contract.fields.job_description'))
                        ->columnSpanFull(),

                    RichEditor::make('terms_and_conditions')
                        ->label(__('hr::employment_contract.fields.terms_and_conditions'))
                        ->columnSpanFull(),
                ])
                ->columnSpanFull(),
        ]);
    }
}
