<?php

return [
    // Basic Information
    'basic_information' => 'زانیاری بنەڕەتی',
    'basic_information_description' => 'وردەکاری ناسنامەی کارمەند و زانیاری پەیوەندی',

    'fields' => [
        'employee_number' => 'ژمارەی کارمەند',
    ],

    'employee_number' => 'ژمارەی کارمەند',
    'first_name' => 'ناوی یەکەم',
    'last_name' => 'ناوی کۆتایی',
    'email' => 'ناونیشانی ئیمەیڵ',
    'phone' => 'ژمارەی تەلەفۆن',

    // Organizational Details
    'organizational_details' => 'وردەکاریەکانی ڕێکخراوی',
    'organizational_details_description' => 'بەش و پۆست و پێکهاتەی بەڕێوەبردن',
    'department' => 'بەش',
    'position' => 'پۆست',
    'manager' => 'بەڕێوەبەر',
    'user_account' => 'هەژماری بەکارهێنەر',

    // Personal Information
    'personal_information' => 'زانیاری کەسی',
    'personal_information_description' => 'وردەکاری کەسی و بەڵگەنامەکانی ناسنامە',
    'date_of_birth' => 'ڕێکەوتی لەدایکبوون',
    'gender' => 'ڕەگەز',
    'gender_male' => 'نێر',
    'gender_female' => 'مێ',
    'gender_other' => 'هیتر',
    'marital_status' => 'دۆخی هاوسەرگیری',
    'marital_status_single' => 'سەڵت',
    'marital_status_married' => 'هاوسەرگیری کردوو',
    'marital_status_divorced' => 'جیابووەوە',
    'marital_status_widowed' => 'بێوەژن',
    'nationality' => 'نەتەوایەتی',
    'national_id' => 'ژمارەی ناسنامەی نیشتیمانی',
    'passport_number' => 'ژمارەی پاسپۆرت',

    // Address Information
    'address_information' => 'زانیاری ناونیشان',
    'address_information_description' => 'ناونیشانی نیشتەجێبوون و وردەکاری شوێن',
    'address_line_1' => 'ناونیشانی یەکەم',
    'address_line_2' => 'ناونیشانی دووەم',
    'city' => 'شار',
    'state' => 'ویلایەت/پارێزگا',
    'zip_code' => 'کۆدی پۆستە',
    'country' => 'وڵات',

    // Emergency Contact
    'emergency_contact' => 'پەیوەندی لەکاتی فریاکەوتندا',
    'emergency_contact_description' => 'وردەکاری کەسی پەیوەندی لەکاتی فریاکەوتندا',
    'emergency_contact_name' => 'ناوی کەسی پەیوەندی',
    'emergency_contact_phone' => 'تەلەفۆنی کەسی پەیوەندی',
    'emergency_contact_relationship' => 'پەیوەندی خزمایەتی',

    // Employment Details
    'employment_details' => 'وردەکاریەکانی کارکردن',
    'employment_details_description' => 'ڕێکەوتەکانی کارکردن و دۆخ و جۆر',
    'hire_date' => 'ڕێکەوتی دامەزراندن',
    'termination_date' => 'ڕێکەوتی کۆتایی خزمەتگوزاری',
    'employment_status' => 'دۆخی کارکردن',
    'employment_status_active' => 'چالاک',
    'employment_status_inactive' => 'ناچالاک',
    'employment_status_terminated' => 'کۆتایی خزمەتگوزاری',
    'employment_status_on_leave' => 'لە پشوودا',
    'employee_type' => 'جۆری کارمەند',
    'employee_type_full_time' => 'کاتی تەواو',
    'employee_type_part_time' => 'کاتی بەشی',
    'employee_type_contract' => 'گرێبەست',
    'employee_type_intern' => 'ڕاهێنەر',
    'is_active' => 'چالاک',

    // Banking Information
    'banking_information' => 'زانیاری بانکی',
    'banking_information_description' => 'وردەکاری هەژماری بانکی بۆ مووچە',
    'bank_name' => 'ناوی بانک',
    'bank_account_number' => 'ژمارەی هەژمار',
    'bank_routing_number' => 'ژمارەی ڕێنیشاندەر',
    'autogenerated' => 'خۆکاری',

    // Navigation
    'navigation_label' => 'کارمەندان',
    'navigation_group' => 'سەرچاوە مرۆییەکان',

    'label' => 'کارمەند',
    'create' => 'دروستکردنی کارمەند',
];
