<?php

namespace Kezi\Accounting\Filament\Clusters\Accounting\Resources\Assets\RelationManagers;

use Exception;
use \Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;
use Kezi\Accounting\Enums\Assets\DepreciationEntryStatus;
use Kezi\Accounting\Models\DepreciationEntry;

/**
 * @extends RelationManager<\Kezi\Accounting\Models\Asset>
 */
class DepreciationEntryRelationManager extends RelationManager
{
    protected static string $relationship = 'depreciationEntries';

    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('accounting::asset.depreciation_entries');
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                // No form needed as entries are generated by the service
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('depreciation_date')
            ->columns([
                TextColumn::make('depreciation_date')
                    ->label(__('accounting::asset.depreciation_date'))
                    ->date(),
                TextColumn::make('amount')
                    ->label(__('accounting::asset.amount')),
                TextColumn::make('status')
                    ->label(__('accounting::asset.status')),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                // No header actions needed
            ])
            ->actions([
                Action::make('post')
                    ->label(__('accounting::asset.post'))
                    ->action(fn (DepreciationEntry $record) => $this->postDepreciation($record))
                    ->requiresConfirmation()
                    ->visible(fn (DepreciationEntry $record): bool => $record->status === DepreciationEntryStatus::Draft),
            ])
            ->bulkActions([
                // No bulk actions needed
            ]);
    }

    public function postDepreciation(DepreciationEntry $entry): void
    {
        $user = request()->user();
        if (! $user) {
            throw new Exception('User must be authenticated to post depreciation');
        }
        app(\Kezi\Accounting\Services\AssetService::class)->postDepreciation($entry, $user);
        Notification::make()
            ->title(__('accounting::asset.post_depreciation_success'))
            ->success()
            ->send();
    }
}
