<?php

namespace Modules\Accounting\Filament\Clusters\Accounting\Resources\Assets\RelationManagers;

use App\Enums\Assets\DepreciationEntryStatus;
use App\Models\DepreciationEntry;
use App\Services\AssetService;
use Filament\Actions\Action;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class DepreciationEntryRelationManager extends RelationManager
{
    protected static string $relationship = 'depreciationEntries';

    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('asset.depreciation_entries');
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                // No form needed as entries are generated by the service
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('depreciation_date')
            ->columns([
                TextColumn::make('depreciation_date')
                    ->label(__('asset.depreciation_date'))
                    ->date(),
                TextColumn::make('amount')
                    ->label(__('asset.amount')),
                TextColumn::make('status')
                    ->label(__('asset.status')),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                // No header actions needed
            ])
            ->recordActions([
                Action::make('post')
                    ->label(__('asset.post'))
                    ->action(fn (\Modules\Accounting\Models\DepreciationEntry $record) => $this->postDepreciation($record))
                    ->requiresConfirmation()
                    ->visible(fn (\Modules\Accounting\Models\DepreciationEntry $record): bool => $record->status === DepreciationEntryStatus::Draft),
            ])
            ->toolbarActions([
                // No bulk actions needed
            ]);
    }

    public function postDepreciation(\Modules\Accounting\Models\DepreciationEntry $entry): void
    {
        $user = request()->user();
        if (! $user) {
            throw new \Exception('User must be authenticated to post depreciation');
        }
        app(\Modules\Accounting\Services\AssetService::class)->postDepreciation($entry, $user);
        \Filament\Notifications\Notification::make()
            ->title(__('asset.post_depreciation_success'))
            ->success()
            ->send();
    }
}
